spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/digvijay.sunil/IdeaProjects/koerber-training/currency_app/config
          clone-on-start: true
          default-label: master
  application:
    name:
      config-server
management:
  endpoints:
    web:
      exposure:
        include: health,refresh,env
server:
  port: 8888