global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'currency-exchange'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'currency-conversion'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8100']
