spring:
  application:
    name: gateway
  cloud:
    gateway:
#      routes:
#        - id: currency-exchange
#          uri: lb://currency-exchange
#          predicates:
#            - Path=/currency-exchange/**
#          filters:
#            - TokenRelay
#        - id: currency-conversion
#          uri: lb://currency-conversion
#          predicates:
#            - Path=/currency-conversion/**
#          filters:
#            - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8765

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      shutdown:
        enabled: true
      health:
        enabled: true
    info:
      env:
        enabled: true
    health:
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


security:
  oauth2:
    client:
      provider:
        keycloak:
          issuer-uri: http://localhost:8081/realms/currency-realm
      registration:
        api-gateway:
          provider: keycloak
          client-id: api-gateway
#          client-secret: <CLIENT_SECRET>
#          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8765/login/oauth2/code/keycloak
